spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # não recomendado em produção, utilizar apenas em estudos
    show-sql: true